[package]
name = "vtig"
version = "0.1.0"
authors = ["jim <jimshawster@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap="3"
fxhash="*"


[profile.dev]
opt-level = 3
